### ISSUE TITLE
[BUG] New releases are missing on ForgeVTT

### ISSUE THREAD

**Issue by ZwS** [League-of-Foundry-Developers/fvtt-module-theatre#153]
Seems that Forge is missing new releases of the module.
https://eu.forge-vtt.com/bazaar/package/theatre shows that latest version is 2.6.1

It probably takes version from https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/blob/728bc6fa1a6091be4d6dfbabb9245a07231aac35/src/module.json#L5

It's kinda critical for Forge , since modules that are installed manually (not via bazaar) took assets space.

**Comment by TheNittles** [comment]
Also having this issue. And it also hasn't update on the main foundry site
https://foundryvtt.com/packages/theatre

Must have been some issue with the newest update.

**Comment by megahead11** [comment]
Just in case you were unaware, the release do not unfortunately pull to the foundry server unless people from the league put in a request to pull the latest version. I do not own the foundry page myself, unfortunately :c 
I'm working on trying to get ownership of the foundry page myself so this isn't a problem in the future, but the people in charge of pulling update versions take a bit to get to me.

**Comment by megahead11** [comment]
Also, an addendum; there are some issues with 2.7.0+ that might need to be addressed before I can recommend updates and releases for it but, I'm trying to find the best way forward. The code for theatre is community contributed so I'm hoping we can see a couple fixes.

**Comment by elizeuangelo** [comment]
Hello there! I'm not sure if you guys had already figured out the issue, but I'm pretty sure this is happening because of a typo:

This is the manifest URL contained within the manifest v2.6.1: `https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/download/latest/module.json`

It doesn't point to the latest release, but to the release named as `LATEST`: `https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/tag/latest`

To correct this... you guys need to update that LATEST release page using the manifest + module.zip from v2.8.0, I checked out and on v2.8.0 manifest the URL is correct: `https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/latest/download/module.json` meaning you wouldnt need to update that release no longer after patching it.

**Comment by megahead11** [comment]
Gotcha! Thanks, I managed to catch that. I wish I knew about this a lot sooner, as it would've cut down a good number of redundant issues lmao.
It should be fixed, though I will likely be pushing another one soon.

**Comment by megahead11** [comment]
Please let me know if after the next release, the forge is able to pull v2.8.1

**Comment by Zepppi** [comment]
I have noticed that no matter how many times I have refreshed/clicked updates. Forge still shows v2.8.0

**Comment by Almaity** [comment]
Hi, Forge is still stuck on 2.8.0, which doesn't function with v12 at all (literally doesn't show the in the modules list.) I see the v12 issue is solved supposdely, so digging around I finally figured out its just the module not actually updating that's the issue.

**Comment by megahead11** [comment]
That's strange. I believe the official link on the foundry module page may not be pointing to the latest version, which is odd because I recently had that bumped. 
I will see what I can do about this.
